# Site settings
title: lucasfcosta
full_name: Lucas Fernandes da Costa
email: lucas@lucasfcosta.com
description: > # 
  Coding, culture and life in general.
  Yes, it's that wide.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucasfcosta.com" # the base hostname & protocol for your site
github_username:  lucasfcosta
linkedin_username: lucasfdacosta
twitter_username: lfernandescosta
paginate: 5
paginate_path: "/posts/page:num/"

# Collections
collections:
  talks:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
timezone: Europe/London
plugins: [jekyll-paginate]
